services:
  api:
    build: .
    container_name: travel-planned-api
    ports:
      - ${API_PORT}:3333
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_BASE_URL=${API_BASE_URL}
      - WEB_BASE_URL=${WEB_BASE_URL}
    depends_on:
      - postgres
    networks:
      - api

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: travel-planned-DB
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - api

networks:
  api:
    driver: bridge