-- AlterTable
ALTER TABLE "activities" ALTER COLUMN "occurs_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "trips" ALTER COLUMN "starts_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "ends_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);
