name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: "ubuntu-latest"

    # Biuldar imagem com versão usando tag do versionamento

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA Tag
        id: generate_sha_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker Image
        run: docker build -t rickphp/travel-planned-api:${{ steps.generate_sha_tag.outputs.sha }} .

    # Logar no container registry

    #Enviar imagem para o Docker hub
